<a href="https://colab.research.google.com/github/FairuzFernanda30/Latihan/blob/main/panda%2CSeaborn%2CMtplot.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [5]:
import numpy as np
# Create an array
civilian_birth = np.array([4352, 233, 3245, 256, 2394])
civilian_birth

np.zeros((3, 6 )) # special array with numpy

np.linspace(0,1,5) # 0 to 1 inklusif dengan 5 point

a = np.array([0,1])
b = np.array([2,3])
ab = np.stack((a,b)).T # menumpuk array
print(ab)

[[0 2]
 [1 3]]


In [7]:
floatVar = 3.145
intVar = floatVar.asty

AttributeError: ignored

In [8]:
A = np.array([[4,5],[6,-3]]) 
b = np.array([23, 3]) 
x,y = np.linalg.solve(A,b) 
print("value of x = ",x,"\n value of y = ",y)

matrix = np.matrix([[1, 5, 3], [9, 5, 6], [2, 8, 9]])
matrix.flatten() # Flatten matrix

np.linalg.det(matrix)  # Return determinant of matrix

matrix.diagonal().sum()  # Calculate the trace of the matrix

np.linalg.inv(matrix) # Calculate inverse of matrix

value of x =  2.0 
 value of y =  3.0


matrix([[ 0.01851852,  0.12962963, -0.09259259],
        [ 0.42592593, -0.01851852, -0.12962963],
        [-0.38271605, -0.01234568,  0.24691358]])

In [10]:
# Invers matrix menggunakan fungsi linalg Inv Numpy
A = np.array ([[4,5],[6,-3]])
A
np.linalg.inv(A)

array([[ 0.07142857,  0.11904762],
       [ 0.14285714, -0.0952381 ]])

In [11]:
matrix = np.matrix([[1,5,3], [9,5,6],[2,8,9]])
matrix

matrix([[1, 5, 3],
        [9, 5, 6],
        [2, 8, 9]])

In [12]:
matrix.diagonal().sum() #diiagonal matrix

15

In [13]:
matrix.flatten() # mendatarkan matrix

matrix([[1, 5, 3, 9, 5, 6, 2, 8, 9]])

#Pandas

In [19]:
import pandas as pd
data = ['a','b','c','d']
s = pd.Series(data) # membuat seri panda
print(s)

data = {'Ngaran' : ['Semar','cepot','Petruk','kabayan'],
        'tahun'  : ['2000','2002','2004','2006'],'Wartos': [2,3,4,7]}

index = ['Kaler','Kulon','Kaler','Kidul'] 
df = pd.DataFrame(data, index = index) # membuat data frame
df

0    a
1    b
2    c
3    d
dtype: object


Ngaran tahun  Wartos
Kaler    Semar  2000       2
Kulon    cepot  2002       3
Kaler   Petruk  2004       4
Kidul  kabayan  2006       7

In [22]:
# Load a csv
url = 'https://raw.githubusercontent.com/anshupandey/WileyNXT/main/DataEngineering/datawh.csv'
df = pd.read_csv(url)
df.head(2)

# Load a JSON file
url = 'https://raw.githubusercontent.com/anshupandey/WileyNXT/main/DataEngineering/server-metrics.json'
df = pd.read_json(url)
df.head(2)

# Save dataframe as csv in the working director
df.to_csv('server_data.csv')

In [24]:
traindata = df [["dates", "Server"]]
traindata

dates     Server
0   1525046400000  Server_02
1   1525132800000  Server_02
2   1525219200000   Server_0
3   1525305600000  Server_01
4   1525392000000   Server_0
5   1525478400000  Server_01
6   1525564800000  Server_01
7   1525651200000  Server_01
8   1525737600000  Server_02
9   1525824000000  Server_01
10  1525910400000   Server_0
11  1525996800000   Server_0
12  1526083200000  Server_01
13  1526169600000  Server_02
14  1526256000000  Server_02
15  1526342400000   Server_0
16  1526428800000  Server_01
17  1526515200000  Server_02
18  1526601600000  Server_02
19  1526688000000  Server_02